{% set name = "py-ed25519-zebra-bindings" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/polkascan/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: af962f873db856d39adb0a2236595611bcd4be63a7bec9183c7ace0deb9b2be3
  patches:
    # - fix-Cargo-pep621.patch
    # - fix-pyproject-pep621.patch

build:
  ignore_prefix_files: true
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vvv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin =0.14.17
    - python
    - pip
    - setuptools-rust
  run:
    - python

test:
  source_files:
    - tests.py
  requires:
    - pip
    - py-bip39-bindings >=0.1.9,<1.0
    - pytest
  commands:
    - pip check
    - pytest -v tests.py

about:
  home: https://github.com/polkascan/py-ed25519-zebra-bindings
  summary: 'Python bindings for the ed25519-zebra RUST crate'

  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - arjanz
    - MementoRC
