{% set name = "py-ed25519-zebra-bindings" %}
{% set version = "1.0.1" %}
{% set sha256 = "1da932dfd48ac2c842aa7215b0f729dfb7f2694619ccd42cf9d101c10bb92135" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/polkascan/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  ignore_prefix_files: True
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vvv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin =0.14.17
    - python
    - pip
    - setuptools-rust
  run:
    - python

test:
  source_files:
    - tests.py
  requires:
    - pip
    - py-bip39-bindings >=0.1.9,<1.0
    - pytest
  commands:
    - pip check
    - pytest -v tests.py

about:
  home: https://github.com/polkascan/py-ed25519-zebra-bindings
  summary: 'Python bindings for the ed25519-zebra RUST crate'

  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - MementoRC
